//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahjong.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mahjong.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream chow {
            get {
                return ResourceManager.GetStream("chow", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap flower1 {
            get {
                object obj = ResourceManager.GetObject("flower1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower2 {
            get {
                object obj = ResourceManager.GetObject("flower2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower3 {
            get {
                object obj = ResourceManager.GetObject("flower3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower4 {
            get {
                object obj = ResourceManager.GetObject("flower4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower5 {
            get {
                object obj = ResourceManager.GetObject("flower5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower6 {
            get {
                object obj = ResourceManager.GetObject("flower6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower7 {
            get {
                object obj = ResourceManager.GetObject("flower7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower8 {
            get {
                object obj = ResourceManager.GetObject("flower8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g1 {
            get {
                object obj = ResourceManager.GetObject("g1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap g2 {
            get {
                object obj = ResourceManager.GetObject("g2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream kong {
            get {
                return ResourceManager.GetStream("kong", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap m1 {
            get {
                object obj = ResourceManager.GetObject("m1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m2 {
            get {
                object obj = ResourceManager.GetObject("m2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream pon {
            get {
                return ResourceManager.GetStream("pon", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope1 {
            get {
                object obj = ResourceManager.GetObject("rope1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope1s {
            get {
                return ResourceManager.GetStream("rope1s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope2 {
            get {
                object obj = ResourceManager.GetObject("rope2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope2s {
            get {
                return ResourceManager.GetStream("rope2s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope3 {
            get {
                object obj = ResourceManager.GetObject("rope3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope3s {
            get {
                return ResourceManager.GetStream("rope3s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope4 {
            get {
                object obj = ResourceManager.GetObject("rope4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope4s {
            get {
                return ResourceManager.GetStream("rope4s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope5 {
            get {
                object obj = ResourceManager.GetObject("rope5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope5s {
            get {
                return ResourceManager.GetStream("rope5s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope6 {
            get {
                object obj = ResourceManager.GetObject("rope6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope6s {
            get {
                return ResourceManager.GetStream("rope6s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope7 {
            get {
                object obj = ResourceManager.GetObject("rope7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope7s {
            get {
                return ResourceManager.GetStream("rope7s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope8 {
            get {
                object obj = ResourceManager.GetObject("rope8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope8s {
            get {
                return ResourceManager.GetStream("rope8s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope9 {
            get {
                object obj = ResourceManager.GetObject("rope9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope9s {
            get {
                return ResourceManager.GetStream("rope9s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten1 {
            get {
                object obj = ResourceManager.GetObject("ten1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten1s {
            get {
                return ResourceManager.GetStream("ten1s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten2 {
            get {
                object obj = ResourceManager.GetObject("ten2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten2s {
            get {
                return ResourceManager.GetStream("ten2s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten3 {
            get {
                object obj = ResourceManager.GetObject("ten3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten3s {
            get {
                return ResourceManager.GetStream("ten3s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten4 {
            get {
                object obj = ResourceManager.GetObject("ten4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten4s {
            get {
                return ResourceManager.GetStream("ten4s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten5 {
            get {
                object obj = ResourceManager.GetObject("ten5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten5s {
            get {
                return ResourceManager.GetStream("ten5s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten6 {
            get {
                object obj = ResourceManager.GetObject("ten6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten6s {
            get {
                return ResourceManager.GetStream("ten6s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten7 {
            get {
                object obj = ResourceManager.GetObject("ten7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten7s {
            get {
                return ResourceManager.GetStream("ten7s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten8 {
            get {
                object obj = ResourceManager.GetObject("ten8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten8s {
            get {
                return ResourceManager.GetStream("ten8s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten9 {
            get {
                object obj = ResourceManager.GetObject("ten9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten9s {
            get {
                return ResourceManager.GetStream("ten9s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe1 {
            get {
                object obj = ResourceManager.GetObject("tobe1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe1s {
            get {
                return ResourceManager.GetStream("tobe1s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe2 {
            get {
                object obj = ResourceManager.GetObject("tobe2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe2s {
            get {
                return ResourceManager.GetStream("tobe2s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe3 {
            get {
                object obj = ResourceManager.GetObject("tobe3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe3s {
            get {
                return ResourceManager.GetStream("tobe3s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe4 {
            get {
                object obj = ResourceManager.GetObject("tobe4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe4s {
            get {
                return ResourceManager.GetStream("tobe4s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe5 {
            get {
                object obj = ResourceManager.GetObject("tobe5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe5s {
            get {
                return ResourceManager.GetStream("tobe5s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe6 {
            get {
                object obj = ResourceManager.GetObject("tobe6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe6s {
            get {
                return ResourceManager.GetStream("tobe6s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe7 {
            get {
                object obj = ResourceManager.GetObject("tobe7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe7s {
            get {
                return ResourceManager.GetStream("tobe7s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe8 {
            get {
                object obj = ResourceManager.GetObject("tobe8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe8s {
            get {
                return ResourceManager.GetStream("tobe8s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe9 {
            get {
                object obj = ResourceManager.GetObject("tobe9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe9s {
            get {
                return ResourceManager.GetStream("tobe9s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap upbarnd {
            get {
                object obj = ResourceManager.GetObject("upbarnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream win {
            get {
                return ResourceManager.GetStream("win", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word1 {
            get {
                object obj = ResourceManager.GetObject("word1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word1s {
            get {
                return ResourceManager.GetStream("word1s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word2 {
            get {
                object obj = ResourceManager.GetObject("word2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word2s {
            get {
                return ResourceManager.GetStream("word2s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word3 {
            get {
                object obj = ResourceManager.GetObject("word3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word3s {
            get {
                return ResourceManager.GetStream("word3s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word4 {
            get {
                object obj = ResourceManager.GetObject("word4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word4s {
            get {
                return ResourceManager.GetStream("word4s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word5 {
            get {
                object obj = ResourceManager.GetObject("word5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word5s {
            get {
                return ResourceManager.GetStream("word5s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word6 {
            get {
                object obj = ResourceManager.GetObject("word6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word6s {
            get {
                return ResourceManager.GetStream("word6s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word7 {
            get {
                object obj = ResourceManager.GetObject("word7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word7s {
            get {
                return ResourceManager.GetStream("word7s", resourceCulture);
            }
        }
    }
}
