//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.832
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahjong.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mahjong.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream chow {
            get {
                return ResourceManager.GetStream("chow", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap flower1 {
            get {
                object obj = ResourceManager.GetObject("flower1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower2 {
            get {
                object obj = ResourceManager.GetObject("flower2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower3 {
            get {
                object obj = ResourceManager.GetObject("flower3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower4 {
            get {
                object obj = ResourceManager.GetObject("flower4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower5 {
            get {
                object obj = ResourceManager.GetObject("flower5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower6 {
            get {
                object obj = ResourceManager.GetObject("flower6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower7 {
            get {
                object obj = ResourceManager.GetObject("flower7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flower8 {
            get {
                object obj = ResourceManager.GetObject("flower8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream kong {
            get {
                return ResourceManager.GetStream("kong", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream pon {
            get {
                return ResourceManager.GetStream("pon", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope1 {
            get {
                object obj = ResourceManager.GetObject("rope1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope1s {
            get {
                return ResourceManager.GetStream("rope1s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope2 {
            get {
                object obj = ResourceManager.GetObject("rope2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope2s {
            get {
                return ResourceManager.GetStream("rope2s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope3 {
            get {
                object obj = ResourceManager.GetObject("rope3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope3s {
            get {
                return ResourceManager.GetStream("rope3s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope4 {
            get {
                object obj = ResourceManager.GetObject("rope4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope4s {
            get {
                return ResourceManager.GetStream("rope4s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope5 {
            get {
                object obj = ResourceManager.GetObject("rope5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope5s {
            get {
                return ResourceManager.GetStream("rope5s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope6 {
            get {
                object obj = ResourceManager.GetObject("rope6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope6s {
            get {
                return ResourceManager.GetStream("rope6s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope7 {
            get {
                object obj = ResourceManager.GetObject("rope7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope7s {
            get {
                return ResourceManager.GetStream("rope7s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope8 {
            get {
                object obj = ResourceManager.GetObject("rope8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope8s {
            get {
                return ResourceManager.GetStream("rope8s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap rope9 {
            get {
                object obj = ResourceManager.GetObject("rope9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream rope9s {
            get {
                return ResourceManager.GetStream("rope9s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten1 {
            get {
                object obj = ResourceManager.GetObject("ten1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten1s {
            get {
                return ResourceManager.GetStream("ten1s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten2 {
            get {
                object obj = ResourceManager.GetObject("ten2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten2s {
            get {
                return ResourceManager.GetStream("ten2s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten3 {
            get {
                object obj = ResourceManager.GetObject("ten3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten3s {
            get {
                return ResourceManager.GetStream("ten3s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten4 {
            get {
                object obj = ResourceManager.GetObject("ten4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten4s {
            get {
                return ResourceManager.GetStream("ten4s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten5 {
            get {
                object obj = ResourceManager.GetObject("ten5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten5s {
            get {
                return ResourceManager.GetStream("ten5s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten6 {
            get {
                object obj = ResourceManager.GetObject("ten6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten6s {
            get {
                return ResourceManager.GetStream("ten6s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten7 {
            get {
                object obj = ResourceManager.GetObject("ten7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten7s {
            get {
                return ResourceManager.GetStream("ten7s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten8 {
            get {
                object obj = ResourceManager.GetObject("ten8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten8s {
            get {
                return ResourceManager.GetStream("ten8s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ten9 {
            get {
                object obj = ResourceManager.GetObject("ten9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ten9s {
            get {
                return ResourceManager.GetStream("ten9s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe1 {
            get {
                object obj = ResourceManager.GetObject("tobe1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe1s {
            get {
                return ResourceManager.GetStream("tobe1s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe2 {
            get {
                object obj = ResourceManager.GetObject("tobe2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe2s {
            get {
                return ResourceManager.GetStream("tobe2s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe3 {
            get {
                object obj = ResourceManager.GetObject("tobe3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe3s {
            get {
                return ResourceManager.GetStream("tobe3s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe4 {
            get {
                object obj = ResourceManager.GetObject("tobe4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe4s {
            get {
                return ResourceManager.GetStream("tobe4s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe5 {
            get {
                object obj = ResourceManager.GetObject("tobe5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe5s {
            get {
                return ResourceManager.GetStream("tobe5s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe6 {
            get {
                object obj = ResourceManager.GetObject("tobe6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe6s {
            get {
                return ResourceManager.GetStream("tobe6s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe7 {
            get {
                object obj = ResourceManager.GetObject("tobe7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe7s {
            get {
                return ResourceManager.GetStream("tobe7s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe8 {
            get {
                object obj = ResourceManager.GetObject("tobe8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe8s {
            get {
                return ResourceManager.GetStream("tobe8s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tobe9 {
            get {
                object obj = ResourceManager.GetObject("tobe9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tobe9s {
            get {
                return ResourceManager.GetStream("tobe9s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap upbarnd {
            get {
                object obj = ResourceManager.GetObject("upbarnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream win {
            get {
                return ResourceManager.GetStream("win", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word1 {
            get {
                object obj = ResourceManager.GetObject("word1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word1s {
            get {
                return ResourceManager.GetStream("word1s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word2 {
            get {
                object obj = ResourceManager.GetObject("word2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word2s {
            get {
                return ResourceManager.GetStream("word2s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word3 {
            get {
                object obj = ResourceManager.GetObject("word3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word3s {
            get {
                return ResourceManager.GetStream("word3s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word4 {
            get {
                object obj = ResourceManager.GetObject("word4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word4s {
            get {
                return ResourceManager.GetStream("word4s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word5 {
            get {
                object obj = ResourceManager.GetObject("word5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word5s {
            get {
                return ResourceManager.GetStream("word5s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word6 {
            get {
                object obj = ResourceManager.GetObject("word6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word6s {
            get {
                return ResourceManager.GetStream("word6s", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap word7 {
            get {
                object obj = ResourceManager.GetObject("word7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream word7s {
            get {
                return ResourceManager.GetStream("word7s", resourceCulture);
            }
        }
    }
}
